### PR TITLE
Fix node.js random segmentation fault due to race condition in YarpJS_Callback::onRead

### LINKED ISSUE #32: Node.js randomly crashes with segmentation fault when reading ports through YarpJS bindings
The issue was initially observed in https://github.com/ami-iit/yarp-openmct (https://github.com/ami-iit/yarp-openmct/issues/51) when running the open-mct based visualization server.

After analyzing the segmentation fault with the npm package 'segfault-handler', we observed that the issue was occurring in the YarpJS.node C++ addon 
```js
const SegfaultHandler = require('segfault-handler');
SegfaultHandler.registerHandler('crash.log');
```
<details>
<summary>_Originally posted by @nunoguedelha in https://github.com/ami-iit/yarp-openmct/issues/51#issuecomment-979435969_
</summary>

## Segfault Handler output

After the segmentation fault occurs, we get the following output log:
```
PID 61103 received SIGSEGV for address: 0x1ca4be280
0   segfault-handler.node               0x00000001015d40b0 _ZL16segfault_handleriP9__siginfoPv + 304
1   libsystem_platform.dylib            0x00007fff6d0685fd _sigtramp + 29
2   ???                                 0x00000001030288c8 0x0 + 4345465032
3   libYARP_os.3.4.3.dylib              0x0000000153392252 _ZNK4yarp2os6Bottle8toStringEv + 18
4   YarpJS.node                         0x00000001059120f2 _ZN26YarpJS_BufferedPort_Bottle16_callback_onReadERNSt3__16vectorIN2v85LocalINS2_5ValueEEENS0_9allocatorIS5_EEEE + 50
5   YarpJS.node                         0x0000000105914a9a _ZN15YarpJS_CallbackI19YarpJS_BufferedPortIN4yarp2os6BottleEEE20_internal_worker_endEP9uv_work_si + 90
6   node                                0x0000000100768f02 uv__work_done + 175
7   node                                0x000000010076a9f4 uv__async_event + 65
8   node                                0x000000010076ab77 uv__async_io + 136
9   node                                0x0000000100778f96 uv__io_poll + 1554
10  node                                0x000000010076b02b uv_run + 321
11  node                                0x000000010064825c _ZN4node5StartEiPPc + 583
12  node                                0x0000000100001834 start + 52
13  ???                                 0x0000000000000002 0x0 + 2
sh: line 1: 61103 Segmentation fault: 11  node ${NODE_DEBUG_OPTION} iCubTelemVizServer.js
```

So, the issue occurs in `YarpJS.node`, which is the C++ Addon generated by the `yarp.js` module implementing the Yarp Javascript bindings and socket bridge.

More precisely, the issue occurs in:
```
<yarp.js repo>/YarpJS/src/YarpJS_BufferedPort_Bottle.cpp:
    --> YarpJS_BufferedPort_Bottle::_callback_onRead(...)
        --> YarpJS_Bottle::ToString()
```

</details>

The issue was reproduced by running a minimalist Javascript code run with node.js command line.
<details>
<summary>_Originally posted by @nunoguedelha in https://github.com/ami-iit/yarp-openmct/issues/51#issuecomment-1010572867_</summary>

## Note

I'm reproducing the issue with a minimalist javascript code executed under the node command line interface:
```js
var yarp = require('./yarp')
var port = yarp.portHandler.open('/yarpjs/left_leg/stateExt:i')
port.onRead(function (bottle){console.log(bottle.toArray())})
yarp.Network.connect('/icubSim/left_leg/stateExt:o','/yarpjs/left_leg/stateExt:i')
```

</details>

We reference in further comments the analysis done in https://github.com/ami-iit/yarp-openmct/issues/51.

### PR DESCRIPTION
**Pull request by nunoguedelha**
Fixes #32 .

### CODE REVIEW

File: YarpJS/include/YarpJS_BufferedPort.h [hunk 1]
```diff
@@ -31,6 +31,8 @@ class YarpJS_BufferedPort : public YarpJS,
 
     virtual void onRead(T &_datum)
     {
+        onReadCallback->lockMutex();
+
```
Comment (nunoguedelha) [inline YarpJS/include/YarpJS_BufferedPort.h:35]: From a design perspective, I think it would be better to avoid locking the mutex through a public method as I did here, this call not being "tied" to a call to `mutex_callback.unlock()` in any way.
In the old design, `mutex_callback.lock()` was done in `YarpJS_Callback<T>::callCallback()` which schedules the execution of `YarpJS_Callback<T>::_internal_worker(...)` and `YarpJS_Callback<T>::_internal_worker_end(...)` through the function call `uv_async_send( &(this->async) )`. `YarpJS_Callback<T>::_internal_worker_end(...)` calls the `mutex_callback.unlock()`.

For this reason I think it would be better to lock the mutex then latch the `_datum` content (copy to `this->datum`), **both** from `YarpJS_Callback<T>::callCallback()`.

Comment (nunoguedelha) [reply YarpJS/include/YarpJS_BufferedPort.h:35]: I'm pushing an alternative solution...
@traversaro , who else could we assign as reviewer for this kind of change?

Comment (traversaro) [reply YarpJS/include/YarpJS_BufferedPort.h:35]: > @traversaro , who else could we assign as reviewer for this kind of change? @Nicogene ?

Good idea!

**Comment by traversaro** [comment]
@nunoguedelha is this PR still in draft?

**Comment by nunoguedelha** [comment]
> @nunoguedelha is this PR still in draft?

Yes @traversaro , I'm pushing a new commit today with a cleaner implementation.

File: YarpJS/include/YarpJS_BufferedPort.h (hunk 1 above)
Comment (Nicogene) [reply YarpJS/include/YarpJS_BufferedPort.h:35]: I never worked with/on yarp.js and I know very few about javascript, sorry :(

File: YarpJS/include/YarpJS_Callback.h [hunk 2]
```diff
@@ -130,10 +131,22 @@ void YarpJS_Callback<T>::_internal_worker_end(uv_work_t *req, int status)
 template <class T>
 void YarpJS_Callback<T>::callCallback()
 {
+    mutex_callback.lock();
 
+    if(callback!=NULL)
+        uv_async_send( &(this->async) );
```
Comment (traversaro) [inline YarpJS/include/YarpJS_Callback.h:137]: It is probably clear for you, but just for me for understanding: in the case `callback!=NULL`, who/where is being called `mutex_callback.unlock()` that match the earlier `mutex_callback.lock()`?

Comment (nunoguedelha) [reply YarpJS/include/YarpJS_Callback.h:137]: It is called in `YarpJS_Callback<T>::_internal_worker_end(...)`, which were scheduled by `YarpJS_Callback<T>::_internal_async`, itself scheduled by `uv_async_init` in `YarpJS_Callback<T>::setCallback`.

Those are then triggered through `uv_async_send()` in case `callback!=NULL`.

Comment (nunoguedelha) [reply YarpJS/include/YarpJS_Callback.h:137]: Sorry, just realized I explained the same as before in https://github.com/robotology/yarp.js/pull/33#pullrequestreview-851910443, so maybe you want additional details... let me know.

Comment (traversaro) [reply YarpJS/include/YarpJS_Callback.h:137]: No, thanks this is super clear, I had forgot about https://github.com/robotology/yarp.js/pull/33#pullrequestreview-851910443 .

**Review by traversaro — APPROVED** [review]

**Comment by nunoguedelha** [comment]
Thanks @traversaro !
